/**
 * بنية المقياس التشغيلي — 300 درجة (BR-01: 75 + 135 + 90).
 *
 * الأوزان والدوريات هنا هي الإعداد الافتراضي المشتق من وثيقة التحليل،
 * وجميعها قابلة للتعديل لاحقًا من شاشة «إدارة المقياس» دون تعديل الكود.
 */

export const FRAMEWORK = [
  {
    code: 'S1',
    name: 'البيئة والمرافق والتجهيزات',
    weight: 75,
    axes: [
      {
        code: 'A1.1',
        name: 'تهيئة القاعات',
        weight: 30,
        indicators: [{
          code: 'I-1.1.1',
          name: 'تهيئة القاعة قبل بدء الدرس',
          weight: 30,
          tool: 'checklist',
          owner_role: 'supervisor',
          periodicity: 'per_session_sample',
          sample_pct: 50,
          min_count: 2,
          description: 'BR-05: عينة لا تقل عن 50% من اللقاءات، يتم التحقق قبل بدء الدرس.',
          items: [
            'القاعة نظيفة ومهيأة قبل وقت بدء الدرس.',
            'ترتيب المقاعد مناسب لعدد الطلاب وطبيعة الدرس.',
            'الإضاءة كافية وموزعة بشكل مناسب.',
            'التهوية والتكييف يعملان بشكل مريح.',
            'القاعة هادئة وخالية من المشتتات.',
            'السبورة وأدواتها متوفرة وصالحة للاستخدام.',
            'لوحة البرنامج والتعليمات معروضة وواضحة.',
          ],
        }],
      },
      {
        code: 'A1.2',
        name: 'التجهيزات والوسائل',
        weight: 20,
        indicators: [{
          code: 'I-1.2.1',
          name: 'جاهزية التجهيزات والوسائل التعليمية',
          weight: 20,
          tool: 'checklist',
          owner_role: 'supervisor',
          periodicity: 'fixed_count',
          min_count: 2,
          description: 'BR-07: تحقق مرتان على الأقل، ويعاد التحقق عند تغيير القاعة أو حدوث عطل.',
          items: [
            'جهاز العرض يعمل بكفاءة ووضوح.',
            'الصوتيات واضحة وتغطي القاعة.',
            'التوصيلات الكهربائية آمنة ومرتبة.',
            'الوسائل التعليمية المطلوبة متوفرة.',
            'توجد خطة بديلة جاهزة عند تعطل أي جهاز.',
          ],
        }],
      },
      {
        code: 'A1.3',
        name: 'الضيافة',
        weight: 15,
        indicators: [{
          code: 'I-1.3.1',
          name: 'تنظيم الضيافة وسلامتها',
          weight: 15,
          tool: 'checklist',
          owner_role: 'program_officer',
          periodicity: 'per_session_sample',
          sample_pct: 25,
          min_count: 2,
          description: 'BR-06: عينة لا تقل عن 25% من اللقاءات وبحد أدنى مرتين.',
          items: [
            'الضيافة متوفرة في موعدها المحدد.',
            'الكمية مناسبة لعدد الحضور.',
            'سلامة الحفظ والتقديم وصلاحية المواد.',
            'مكان التقديم نظيف ومنظم.',
          ],
        }],
      },
      {
        code: 'A1.4',
        name: 'سلامة المرافق والأمن',
        weight: 10,
        indicators: [{
          code: 'I-1.4.1',
          name: 'سلامة المرافق ومسارات الطوارئ',
          weight: 10,
          tool: 'checklist',
          owner_role: 'supervisor',
          periodicity: 'fixed_count',
          min_count: 2,
          items: [
            'دورات المياه نظيفة ومتاحة للطلاب.',
            'مخارج الطوارئ سالكة وواضحة اللوحات.',
            'طفايات الحريق صالحة وفي أماكنها المخصصة.',
            'حقيبة الإسعافات الأولية متوفرة وصالحة.',
            'محيط المبنى ومداخله آمنة للطلاب.',
          ],
        }],
      },
    ],
  },
  {
    code: 'S2',
    name: 'الجودة العلمية والمحتوى والمعلم',
    weight: 135,
    axes: [
      {
        code: 'A2.1',
        name: 'مناسبة المعلم',
        weight: 25,
        indicators: [{
          code: 'I-2.1.1',
          name: 'التحقق من مناسبة المعلم عبر وثائق أو تزكية معتبرة',
          weight: 25,
          tool: 'checklist',
          owner_role: 'academic_quality',
          periodicity: 'before_start',
          items: [
            'توفر وثيقة علمية أو تزكية معتبرة للمعلم.',
            'تخصص المعلم وخبرته مناسبان للمادة المسندة إليه.',
            'لدى المعلم خبرة سابقة في التدريس لهذه الفئة.',
            'التزام المعلم بالضوابط الشرعية والنظامية للجمعية.',
            'إحاطة المعلم بأهداف البرنامج ومخرجاته قبل البدء.',
          ],
        }],
      },
      {
        code: 'A2.2',
        name: 'جودة وسلامة المحتوى العلمي',
        weight: 30,
        indicators: [{
          code: 'I-2.2.1',
          name: 'سلامة المحتوى العلمي ومناسبته للفئة',
          weight: 30,
          tool: 'checklist',
          owner_role: 'academic_quality',
          periodicity: 'before_start',
          description: 'BR-12: لا يحكم الطالب على السلامة العلمية للمحتوى — القياس بقائمة تحقق متخصصة فقط.',
          items: [
            'المادة سليمة وخالية من الأخطاء العلمية.',
            'المحتوى موافق للمنهج أو المرجع المعتمد.',
            'المحتوى مناسب للفئة العمرية والمستوى المعرفي.',
            'خلو المحتوى من المخالفات الشرعية أو النظامية.',
            'المصادر والمراجع موثّقة وواضحة.',
            'تدرّج المحتوى منطقي من الأساسي إلى المتقدم.',
          ],
        }],
      },
      {
        code: 'A2.3',
        name: 'الخطة والأهداف والمخرجات',
        weight: 20,
        indicators: [{
          code: 'I-2.3.1',
          name: 'وضوح الأهداف والمخرجات والجدول الزمني قبل البدء',
          weight: 20,
          tool: 'checklist',
          owner_role: 'academic_quality',
          periodicity: 'before_start',
          items: [
            'الأهداف مكتوبة وقابلة للقياس.',
            'المخرجات محددة ومرتبطة بالأهداف.',
            'الجدول الزمني معتمد وموزّع على اللقاءات.',
            'اعتماد الخطة موثّق قبل بدء البرنامج.',
            'توجد آلية معتمدة لتوثيق أي تغيير على الخطة.',
          ],
        }],
      },
      {
        code: 'A2.4',
        name: 'تنفيذ المحتوى والتسلسل والتوقيت',
        weight: 25,
        indicators: [{
          code: 'I-2.4.1',
          name: 'تنفيذ المحتوى المقرر والالتزام بالتسلسل والتوقيت',
          weight: 25,
          tool: 'checklist',
          owner_role: 'academic_quality',
          periodicity: 'per_session_sample',
          sample_pct: 30,
          min_count: 2,
          items: [
            'تم تنفيذ موضوع اللقاء وفق الخطة المعتمدة.',
            'الالتزام بتسلسل المحتوى دون قفز أو تكرار غير مبرر.',
            'بدأ اللقاء وانتهى في وقته المحدد.',
            'تمت تغطية زمن اللقاء دون حشو أو اختصار مخل.',
            'أي تغيير على المقرر موثّق ومعتمد.',
          ],
        }],
      },
      {
        code: 'A2.5',
        name: 'الأنشطة والتطبيقات الإثرائية',
        weight: 15,
        indicators: [{
          code: 'I-2.5.1',
          name: 'فاعلية النشاط الرئيس',
          weight: 15,
          tool: 'survey',
          owner_role: 'academic_quality',
          periodicity: 'per_main_activity',
          description: 'BR-09: تُقاس فاعلية النشاط الرئيس مباشرة بعد كل نشاط عبر استبانة من 3 أسئلة.',
        }],
      },
      {
        code: 'A2.6',
        name: 'تقييم المعلم',
        weight: 20,
        indicators: [{
          code: 'I-2.6.1',
          name: 'تقييم الطلاب لأداء المعلم',
          weight: 20,
          tool: 'survey',
          owner_role: 'academic_quality',
          periodicity: 'mid_end',
          description: 'تقييم المعلم في منتصف البرنامج ونهايته.',
        }],
      },
    ],
  },
  {
    code: 'S3',
    name: 'تجربة الطالب والانضباط والاستمرارية',
    weight: 90,
    axes: [
      {
        code: 'A3.1',
        name: 'الدعم والإرشاد والتواصل',
        weight: 20,
        indicators: [{
          code: 'I-3.1.1',
          name: 'الدعم والإرشاد والتواصل مع الطالب',
          weight: 20,
          tool: 'survey',
          owner_role: 'quality_officer',
          periodicity: 'mid_end',
          description: 'BR-08: قياس في منتصف البرنامج ونهايته.',
        }],
      },
      {
        code: 'A3.2',
        name: 'الرضا والانتماء والتوصية',
        weight: 20,
        indicators: [{
          code: 'I-3.2.1',
          name: 'الرضا والانتماء والتوصية والرغبة في الاستمرار',
          weight: 20,
          tool: 'survey',
          owner_role: 'quality_officer',
          periodicity: 'end',
        }],
      },
      {
        code: 'A3.3',
        name: 'المتابعة والانضباط',
        weight: 15,
        indicators: [
          {
            code: 'I-3.3.1',
            name: 'انتظام حضور الطلاب',
            weight: 10,
            tool: 'record',
            owner_role: 'program_officer',
            periodicity: 'continuous',
            record_rule: 'attendance_rate',
            description: 'نسبة الحضور المحتسبة من سجل الحضور (الحضور والتأخر والعذر ضمن المحتسب).',
          },
          {
            code: 'I-3.3.2',
            name: 'توثيق الحالات المتعثرة وإجراءاتها',
            weight: 5,
            tool: 'record',
            owner_role: 'program_officer',
            periodicity: 'continuous',
            record_rule: 'discipline_documented',
          },
        ],
      },
      {
        code: 'A3.4',
        name: 'الشكاوى والمقترحات',
        weight: 15,
        indicators: [{
          code: 'I-3.4.1',
          name: 'معالجة الشكاوى ضمن المدة المعتمدة',
          weight: 15,
          tool: 'record',
          owner_role: 'program_officer',
          periodicity: 'continuous',
          record_rule: 'complaint_sla',
        }],
      },
      {
        code: 'A3.5',
        name: 'استمرارية الطلاب',
        weight: 20,
        indicators: [
          {
            code: 'I-3.5.1',
            name: 'نية الاستمرار',
            weight: 5,
            tool: 'record',
            owner_role: 'quality_officer',
            periodicity: 'end',
            record_rule: 'continuity_intent',
            description: 'BR-10: 5 درجات لنية الاستمرار، تُسجَّل على مستوى الطالب في نهاية البرنامج.',
          },
          {
            code: 'I-3.5.2',
            name: 'الاستمرار الفعلي',
            weight: 15,
            tool: 'record',
            owner_role: 'program_officer',
            periodicity: 'end',
            record_rule: 'continuity_actual',
            description: 'BR-10: 15 درجة للاستمرار الفعلي = المستمرون ÷ أعداد البداية.',
          },
        ],
      },
    ],
  },
];

/** بنك الأسئلة المرتبط بالمؤشرات — البند 9: «مكتبة أسئلة». */
export const QUESTION_BANK = [
  // تقييم المعلم — منتصف ونهاية
  { code: 'Q-T1', indicator: 'I-2.6.1', point: 'mid', text: 'يشرح المعلم المادة بأسلوب واضح ومفهوم.' },
  { code: 'Q-T2', indicator: 'I-2.6.1', point: 'mid', text: 'يلتزم المعلم ببداية اللقاء ونهايته في وقتهما.' },
  { code: 'Q-T3', indicator: 'I-2.6.1', point: 'mid', text: 'يتعامل المعلم مع الطلاب باحترام ويشجعهم على المشاركة.' },
  { code: 'Q-T4', indicator: 'I-2.6.1', point: 'mid', text: 'يجيب المعلم عن أسئلتي واستفساراتي بشكل كافٍ.' },
  { code: 'Q-T1E', indicator: 'I-2.6.1', point: 'end', text: 'يشرح المعلم المادة بأسلوب واضح ومفهوم.' },
  { code: 'Q-T2E', indicator: 'I-2.6.1', point: 'end', text: 'يلتزم المعلم ببداية اللقاء ونهايته في وقتهما.' },
  { code: 'Q-T3E', indicator: 'I-2.6.1', point: 'end', text: 'يتعامل المعلم مع الطلاب باحترام ويشجعهم على المشاركة.' },
  { code: 'Q-T4E', indicator: 'I-2.6.1', point: 'end', text: 'يجيب المعلم عن أسئلتي واستفساراتي بشكل كافٍ.' },
  // الدعم والإرشاد والتواصل — منتصف ونهاية (BR-08)
  { code: 'Q-S1', indicator: 'I-3.1.1', point: 'mid', text: 'أجد من يوجهني ويساعدني عند الحاجة أثناء البرنامج.' },
  { code: 'Q-S2', indicator: 'I-3.1.1', point: 'mid', text: 'تصلني المعلومات والتنبيهات المتعلقة بالبرنامج في وقتها.' },
  { code: 'Q-S3', indicator: 'I-3.1.1', point: 'mid', text: 'أستطيع إيصال ملاحظاتي أو شكواي بسهولة ويُستجاب لها.' },
  { code: 'Q-S1E', indicator: 'I-3.1.1', point: 'end', text: 'أجد من يوجهني ويساعدني عند الحاجة أثناء البرنامج.' },
  { code: 'Q-S2E', indicator: 'I-3.1.1', point: 'end', text: 'تصلني المعلومات والتنبيهات المتعلقة بالبرنامج في وقتها.' },
  { code: 'Q-S3E', indicator: 'I-3.1.1', point: 'end', text: 'أستطيع إيصال ملاحظاتي أو شكواي بسهولة ويُستجاب لها.' },
  // الرضا والانتماء والتوصية — النهاية
  { code: 'Q-R1', indicator: 'I-3.2.1', point: 'end', text: 'أنا راضٍ عن تجربتي في هذا البرنامج بشكل عام.' },
  { code: 'Q-R2', indicator: 'I-3.2.1', point: 'end', text: 'أشعر بالانتماء لجمعية تحصيل المعرفة.' },
  { code: 'Q-R3', indicator: 'I-3.2.1', point: 'end', text: 'أنصح أصدقائي وزملائي بالالتحاق ببرامج الجمعية.' },
  { code: 'Q-R4', indicator: 'I-3.2.1', point: 'end', text: 'لدي الرغبة في الاستمرار والتسجيل في برنامج قادم.' },
  // فاعلية النشاط الرئيس — 3 أسئلة (BR-09)
  { code: 'Q-A1', indicator: 'I-2.5.1', point: 'activity', text: 'كان النشاط مفيدًا وأضاف لي معرفة أو مهارة جديدة.' },
  { code: 'Q-A2', indicator: 'I-2.5.1', point: 'activity', text: 'كان تنظيم النشاط وإدارته جيدًا.' },
  { code: 'Q-A3', indicator: 'I-2.5.1', point: 'activity', text: 'أرغب في المشاركة في أنشطة مشابهة مستقبلًا.' },
];

export const LIKERT = [
  { value: 5, label: 'موافق بشدة' },
  { value: 4, label: 'موافق' },
  { value: 3, label: 'محايد' },
  { value: 2, label: 'غير موافق' },
  { value: 1, label: 'غير موافق بشدة' },
];
