/**
 * بنية المقياس التشغيلي — 300 درجة (BR-01: 75 + 135 + 90).
 * الإصدار الثاني: إعادة هيكلة المحاور، وإضافة الزيارة الصفية كمصدر ثانٍ
 * لتقييم المعلم إلى جانب استبانة الطلاب.
 *
 * الأوزان والدوريات هنا هي الإعداد الافتراضي، وجميعها قابلة للتعديل
 * من شاشة «إدارة المقياس» دون تعديل الكود.
 */

export const SCALE_VERSION = 'v2-300';

export const FRAMEWORK = [
  {
    code: 'S1',
    name: 'جودة البيئة والمرافق',
    weight: 75,
    axes: [
      {
        code: 'A1.1',
        name: 'ملاءمة القاعات للتعلم',
        weight: 20,
        indicators: [{
          code: 'I-1.1.1',
          name: 'ملاءمة القاعة للتعلم',
          weight: 20,
          tool: 'checklist',
          owner_role: 'supervisor',
          periodicity: 'fixed_count',
          min_count: 2,
          description: 'تُقاس الملاءمة البنيوية للقاعة مرتين على الأقل، ويُعاد القياس عند تغيير القاعة.',
          items: [
            'سعة القاعة مناسبة لعدد الطلاب المسجلين.',
            'ترتيب المقاعد يخدم نمط الدرس وطبيعة النشاط.',
            'الإضاءة كافية وموزعة بشكل مناسب على القاعة.',
            'التهوية والتكييف يوفران بيئة مريحة للتعلم.',
            'مستوى العزل الصوتي يسمح بالتركيز وسماع المعلم.',
            'القاعة آمنة ومخارج الطوارئ سالكة وواضحة اللوحات.',
            'سهولة الوصول للقاعة ودورات المياه متاحة وقريبة.',
          ],
        }],
      },
      {
        code: 'A1.2',
        name: 'نظافة القاعات والمرافق',
        weight: 20,
        indicators: [{
          code: 'I-1.2.1',
          name: 'نظافة القاعات والمرافق',
          weight: 20,
          tool: 'checklist',
          owner_role: 'supervisor',
          periodicity: 'per_session_sample',
          sample_pct: 50,
          min_count: 2,
          items: [
            'القاعة نظيفة قبل بدء الدرس.',
            'المقاعد والطاولات نظيفة وسليمة.',
            'دورات المياه نظيفة ومزودة بمستلزماتها.',
            'الممرات والمداخل نظيفة ومرتبة.',
            'حاويات النفايات متوفرة وتُفرَّغ دوريًا.',
            'القاعة تُترك نظيفة بعد انتهاء الدرس.',
          ],
        }],
      },
      {
        code: 'A1.3',
        name: 'تهيئة القاعات قبل بدء الدرس',
        weight: 10,
        indicators: [{
          code: 'I-1.3.1',
          name: 'تهيئة القاعة قبل بدء الدرس',
          weight: 10,
          tool: 'checklist',
          owner_role: 'supervisor',
          periodicity: 'per_session_sample',
          sample_pct: 50,
          min_count: 2,
          description: 'BR-05: عينة لا تقل عن 50% من اللقاءات، يتم التحقق قبل بدء الدرس.',
          items: [
            'القاعة مفتوحة ومهيأة قبل الموعد المحدد.',
            'السبورة وأدواتها جاهزة للاستخدام.',
            'الوسائل المطلوبة لهذا الدرس حاضرة في القاعة.',
            'لوحة البرنامج والتعليمات معروضة وواضحة.',
            'القاعة خالية من المشتتات قبل بدء الدرس.',
          ],
        }],
      },
      {
        code: 'A1.4',
        name: 'التجهيزات التعليمية والتقنية',
        weight: 20,
        indicators: [{
          code: 'I-1.4.1',
          name: 'جاهزية التجهيزات التعليمية والتقنية',
          weight: 20,
          tool: 'checklist',
          owner_role: 'supervisor',
          periodicity: 'fixed_count',
          min_count: 2,
          description: 'BR-07: تحقق مرتان على الأقل، ويعاد التحقق عند تغيير القاعة أو حدوث عطل.',
          items: [
            'جهاز العرض يعمل بكفاءة ووضوح.',
            'الصوتيات واضحة وتغطي القاعة.',
            'الشبكة والإنترنت متاحان ومستقران عند الحاجة.',
            'التوصيلات الكهربائية آمنة ومرتبة.',
            'الوسائل التعليمية المطلوبة متوفرة وصالحة.',
            'توجد خطة بديلة جاهزة عند تعطل أي جهاز.',
          ],
        }],
      },
      {
        code: 'A1.5',
        name: 'الضيافة والخدمات المساندة',
        weight: 5,
        indicators: [{
          code: 'I-1.5.1',
          name: 'الضيافة والخدمات المساندة',
          weight: 5,
          tool: 'checklist',
          owner_role: 'program_officer',
          periodicity: 'per_session_sample',
          sample_pct: 25,
          min_count: 2,
          description: 'BR-06: عينة لا تقل عن 25% من اللقاءات وبحد أدنى مرتين.',
          items: [
            'الضيافة متوفرة في موعدها المحدد.',
            'الكمية مناسبة لعدد الحضور.',
            'سلامة الحفظ والتقديم وصلاحية المواد.',
            'مكان التقديم نظيف ومنظم.',
          ],
        }],
      },
    ],
  },
  {
    code: 'S2',
    name: 'جودة العملية التعليمية',
    weight: 135,
    axes: [
      {
        code: 'A2.1',
        name: 'كفاءة المعلم وجودة المحتوى العلمي',
        weight: 50,
        indicators: [
          {
            code: 'I-2.1.1',
            name: 'مناسبة المعلم للمادة',
            weight: 10,
            tool: 'checklist',
            owner_role: 'academic_quality',
            periodicity: 'before_start',
            items: [
              'توفر وثيقة علمية أو تزكية معتبرة للمعلم.',
              'تخصص المعلم وخبرته مناسبان للمادة المسندة إليه.',
              'لدى المعلم خبرة سابقة في التدريس لهذه الفئة.',
              'التزام المعلم بالضوابط الشرعية والنظامية للجمعية.',
              'إحاطة المعلم بأهداف البرنامج ومخرجاته قبل البدء.',
            ],
          },
          {
            code: 'I-2.1.2',
            name: 'تمكن المعلم وجودة تقديمه — استبانة الطلاب',
            weight: 10,
            tool: 'survey',
            owner_role: 'academic_quality',
            periodicity: 'mid_end',
            description: 'المصدر الأول لتقييم المعلم: رأي الطلاب في منتصف البرنامج ونهايته.',
          },
          {
            code: 'I-2.1.3',
            name: 'تمكن المعلم وجودة تقديمه — الزيارة الصفية',
            weight: 10,
            tool: 'checklist',
            owner_role: 'academic_quality',
            periodicity: 'fixed_count',
            min_count: 2,
            description: 'المصدر الثاني لتقييم المعلم: زيارة صفية من مسؤول التخطيط والجودة العلمية '
              + 'مرتين على الأقل في الفصل، وتُحتسب الدرجة كمتوسط نتائج الزيارتين.',
            items: [
              'تمكن المعلم من المادة وسلامة المعلومة المقدَّمة.',
              'وضوح العرض وتدرّجه المنطقي من الأساسي إلى المتقدم.',
              'إدارة زمن الحصة وتوزيعه على عناصر الدرس.',
              'تفاعل الطلاب ومشاركتهم أثناء الدرس.',
              'تنويع أساليب التدريس واستخدام الوسائل المناسبة.',
              'التعامل مع أسئلة الطلاب وتصحيح أخطائهم بأسلوب تربوي.',
              'انضباط القاعة وإدارة السلوك أثناء الدرس.',
              'ربط الدرس بالأهداف والمخرجات المعتمدة في الخطة.',
            ],
          },
          {
            code: 'I-2.1.4',
            name: 'جودة وسلامة ومناسبة المحتوى العلمي',
            weight: 20,
            tool: 'checklist',
            owner_role: 'academic_quality',
            periodicity: 'before_start',
            description: 'BR-12: لا يحكم الطالب على السلامة العلمية للمحتوى — القياس بقائمة تحقق متخصصة فقط.',
            items: [
              'المادة سليمة وخالية من الأخطاء العلمية.',
              'المحتوى موافق للمنهج أو المرجع المعتمد.',
              'المحتوى مناسب للفئة العمرية والمستوى المعرفي.',
              'خلو المحتوى من المخالفات الشرعية أو النظامية.',
              'المصادر والمراجع موثّقة وواضحة.',
              'تدرّج المحتوى منطقي ومترابط.',
            ],
          },
        ],
      },
      {
        code: 'A2.2',
        name: 'الالتزام بالخطة التعليمية',
        weight: 35,
        indicators: [
          {
            code: 'I-2.2.1',
            name: 'وجود خطة تعليمية معتمدة',
            weight: 8,
            tool: 'checklist',
            owner_role: 'academic_quality',
            periodicity: 'before_start',
            items: [
              'توجد خطة تعليمية مكتوبة للبرنامج.',
              'الخطة معتمدة من الجهة المختصة قبل بدء البرنامج.',
              'الخطة تغطي كامل لقاءات البرنامج.',
              'الخطة متاحة للمعلم وفريق البرنامج.',
              'توجد آلية معتمدة لتوثيق أي تعديل على الخطة.',
            ],
          },
          {
            code: 'I-2.2.2',
            name: 'وضوح الأهداف والمخرجات والجدول الزمني',
            weight: 7,
            tool: 'checklist',
            owner_role: 'academic_quality',
            periodicity: 'before_start',
            items: [
              'الأهداف مكتوبة وقابلة للقياس.',
              'المخرجات محددة ومرتبطة بالأهداف.',
              'لكل لقاء هدف ومخرج واضحان.',
              'الجدول الزمني موزّع على اللقاءات بوضوح.',
              'معايير الحكم على تحقق المخرجات محددة مسبقًا.',
            ],
          },
          {
            code: 'I-2.2.3',
            name: 'نسبة تنفيذ المحتوى المقرر',
            weight: 12,
            tool: 'checklist',
            owner_role: 'academic_quality',
            periodicity: 'per_session_sample',
            sample_pct: 30,
            min_count: 2,
            items: [
              'نُفّذ موضوع اللقاء وفق الخطة المعتمدة.',
              'غُطّيت عناصر الموضوع كاملة دون إسقاط.',
              'لم يُختصر المحتوى بشكل مخل بالمخرج.',
              'ما لم يُنفَّذ نُقل إلى خطة تعويض معتمدة.',
              'أي تغيير على المقرر موثّق ومعتمد.',
            ],
          },
          {
            code: 'I-2.2.4',
            name: 'الالتزام بالتوقيت والتسلسل المعتمد',
            weight: 8,
            tool: 'checklist',
            owner_role: 'academic_quality',
            periodicity: 'per_session_sample',
            sample_pct: 30,
            min_count: 2,
            items: [
              'بدأ اللقاء في وقته المحدد.',
              'انتهى اللقاء في وقته المحدد.',
              'التُزم التسلسل المعتمد للمحتوى دون قفز أو تكرار.',
              'استُغل زمن اللقاء دون حشو أو وقت ضائع.',
              'أي تغيير في الترتيب موثّق ومعتمد.',
            ],
          },
        ],
      },
      {
        code: 'A2.3',
        name: 'الأنشطة والتطبيقات الإثرائية',
        weight: 20,
        indicators: [
          {
            code: 'I-2.3.1',
            name: 'تنفيذ الأنشطة والتطبيقات المقررة',
            weight: 12,
            tool: 'checklist',
            owner_role: 'academic_quality',
            periodicity: 'fixed_count',
            min_count: 2,
            items: [
              'نُفّذت الأنشطة والتطبيقات المقررة في الخطة.',
              'الأنشطة مرتبطة بأهداف البرنامج ومخرجاته.',
              'شارك في الأنشطة العدد المستهدف من الطلاب.',
              'نُفّذت الأنشطة في أوقاتها المخططة.',
              'وُثّقت الأنشطة بالشواهد المناسبة.',
            ],
          },
          {
            code: 'I-2.3.2',
            name: 'فاعلية الأنشطة والتطبيقات',
            weight: 8,
            tool: 'survey',
            owner_role: 'academic_quality',
            periodicity: 'per_main_activity',
            description: 'BR-09: تُقاس فاعلية النشاط الرئيس مباشرة بعد كل نشاط عبر استبانة من 3 أسئلة.',
          },
        ],
      },
      {
        code: 'A2.4',
        name: 'المتابعة والانضباط التعليمي',
        weight: 30,
        indicators: [
          {
            code: 'I-2.4.1',
            name: 'متابعة الحضور والانتظام',
            weight: 10,
            tool: 'record',
            owner_role: 'program_officer',
            periodicity: 'continuous',
            record_rule: 'attendance_rate',
            description: 'نسبة الحضور المحتسبة من سجل الحضور (الحضور والتأخر والعذر ضمن المحتسب).',
          },
          {
            code: 'I-2.4.2',
            name: 'تطبيق إجراءات التعثر وعدم الالتزام',
            weight: 8,
            tool: 'record',
            owner_role: 'program_officer',
            periodicity: 'continuous',
            record_rule: 'discipline_documented',
            description: 'نسبة الحالات المسجلة التي وُثّق لها إجراء متخذ.',
          },
          {
            code: 'I-2.4.3',
            name: 'جلسات المتابعة عند الحاجة',
            weight: 6,
            tool: 'record',
            owner_role: 'program_officer',
            periodicity: 'continuous',
            record_rule: 'followup_sessions',
            description: 'نسبة الحالات التي عُقدت لها جلسة متابعة موثّقة بتاريخها.',
          },
          {
            code: 'I-2.4.4',
            name: 'تفعيل قنوات التذكير والمتابعة',
            weight: 6,
            tool: 'checklist',
            owner_role: 'program_officer',
            periodicity: 'fixed_count',
            min_count: 2,
            items: [
              'توجد قناة تواصل معتمدة ومفعّلة مع الطلاب.',
              'تُرسل تذكيرات قبل اللقاءات في وقت مناسب.',
              'يُتابَع الغياب بتواصل مباشر مع الطالب.',
              'تُوثَّق المراسلات والتذكيرات المرسلة.',
              'يُستجاب لاستفسارات الطلاب خلال مدة معقولة.',
            ],
          },
        ],
      },
    ],
  },
  {
    code: 'S3',
    name: 'جودة الدعم وتجربة الطالب',
    weight: 90,
    axes: [
      {
        code: 'A3.1',
        name: 'معالجة الشكاوى والمقترحات',
        weight: 15,
        indicators: [{
          code: 'I-3.1.1',
          name: 'معالجة الشكاوى ضمن المدة المعتمدة',
          weight: 15,
          tool: 'record',
          owner_role: 'program_officer',
          periodicity: 'continuous',
          record_rule: 'complaint_sla',
        }],
      },
      {
        code: 'A3.2',
        name: 'الدعم والإرشاد والتواصل',
        weight: 30,
        indicators: [{
          code: 'I-3.2.1',
          name: 'الدعم والإرشاد والتواصل مع الطالب',
          weight: 30,
          tool: 'survey',
          owner_role: 'quality_officer',
          periodicity: 'mid_end',
          description: 'BR-08: قياس في منتصف البرنامج ونهايته.',
        }],
      },
      {
        code: 'A3.3',
        name: 'الرضا والانتماء',
        weight: 25,
        indicators: [{
          code: 'I-3.3.1',
          name: 'الرضا والانتماء والتوصية',
          weight: 25,
          tool: 'survey',
          owner_role: 'quality_officer',
          periodicity: 'end',
        }],
      },
      {
        code: 'A3.4',
        name: 'استمرارية الطلاب',
        weight: 20,
        indicators: [
          {
            code: 'I-3.4.1',
            name: 'الرغبة في الاستمرار',
            weight: 5,
            tool: 'record',
            owner_role: 'quality_officer',
            periodicity: 'end',
            record_rule: 'continuity_intent',
            description: 'BR-10: 5 درجات للرغبة في الاستمرار، تُسجَّل على مستوى الطالب في نهاية البرنامج.',
          },
          {
            code: 'I-3.4.2',
            name: 'الاستمرارية الفعلية',
            weight: 15,
            tool: 'record',
            owner_role: 'program_officer',
            periodicity: 'end',
            record_rule: 'continuity_actual',
            description: 'BR-10: 15 درجة للاستمرارية الفعلية = المستمرون ÷ أعداد البداية.',
          },
        ],
      },
    ],
  },
];

/** بنك الأسئلة المرتبط بالمؤشرات — البند 9: «مكتبة أسئلة». */
export const QUESTION_BANK = [
  // تمكن المعلم وجودة تقديمه — استبانة الطلاب (منتصف ونهاية)
  { code: 'Q-T1', indicator: 'I-2.1.2', point: 'mid', text: 'يشرح المعلم المادة بأسلوب واضح ومفهوم.' },
  { code: 'Q-T2', indicator: 'I-2.1.2', point: 'mid', text: 'يظهر المعلم تمكنًا علميًا في المادة التي يدرّسها.' },
  { code: 'Q-T3', indicator: 'I-2.1.2', point: 'mid', text: 'يلتزم المعلم ببداية اللقاء ونهايته في وقتهما.' },
  { code: 'Q-T4', indicator: 'I-2.1.2', point: 'mid', text: 'يتعامل المعلم مع الطلاب باحترام ويشجعهم على المشاركة.' },
  { code: 'Q-T5', indicator: 'I-2.1.2', point: 'mid', text: 'يجيب المعلم عن أسئلتي واستفساراتي بشكل كافٍ.' },
  { code: 'Q-T1E', indicator: 'I-2.1.2', point: 'end', text: 'يشرح المعلم المادة بأسلوب واضح ومفهوم.' },
  { code: 'Q-T2E', indicator: 'I-2.1.2', point: 'end', text: 'يظهر المعلم تمكنًا علميًا في المادة التي يدرّسها.' },
  { code: 'Q-T3E', indicator: 'I-2.1.2', point: 'end', text: 'يلتزم المعلم ببداية اللقاء ونهايته في وقتهما.' },
  { code: 'Q-T4E', indicator: 'I-2.1.2', point: 'end', text: 'يتعامل المعلم مع الطلاب باحترام ويشجعهم على المشاركة.' },
  { code: 'Q-T5E', indicator: 'I-2.1.2', point: 'end', text: 'يجيب المعلم عن أسئلتي واستفساراتي بشكل كافٍ.' },
  // الدعم والإرشاد والتواصل — منتصف ونهاية (BR-08)
  { code: 'Q-S1', indicator: 'I-3.2.1', point: 'mid', text: 'أجد من يوجهني ويساعدني عند الحاجة أثناء البرنامج.' },
  { code: 'Q-S2', indicator: 'I-3.2.1', point: 'mid', text: 'تصلني المعلومات والتنبيهات المتعلقة بالبرنامج في وقتها.' },
  { code: 'Q-S3', indicator: 'I-3.2.1', point: 'mid', text: 'أستطيع إيصال ملاحظاتي أو شكواي بسهولة ويُستجاب لها.' },
  { code: 'Q-S4', indicator: 'I-3.2.1', point: 'mid', text: 'يُتابَع غيابي أو تعثري بتواصل مناسب.' },
  { code: 'Q-S1E', indicator: 'I-3.2.1', point: 'end', text: 'أجد من يوجهني ويساعدني عند الحاجة أثناء البرنامج.' },
  { code: 'Q-S2E', indicator: 'I-3.2.1', point: 'end', text: 'تصلني المعلومات والتنبيهات المتعلقة بالبرنامج في وقتها.' },
  { code: 'Q-S3E', indicator: 'I-3.2.1', point: 'end', text: 'أستطيع إيصال ملاحظاتي أو شكواي بسهولة ويُستجاب لها.' },
  { code: 'Q-S4E', indicator: 'I-3.2.1', point: 'end', text: 'يُتابَع غيابي أو تعثري بتواصل مناسب.' },
  // الرضا والانتماء — النهاية
  { code: 'Q-R1', indicator: 'I-3.3.1', point: 'end', text: 'أنا راضٍ عن تجربتي في هذا البرنامج بشكل عام.' },
  { code: 'Q-R2', indicator: 'I-3.3.1', point: 'end', text: 'أشعر بالانتماء لجمعية تحصيل المعرفة.' },
  { code: 'Q-R3', indicator: 'I-3.3.1', point: 'end', text: 'أنصح أصدقائي وزملائي بالالتحاق ببرامج الجمعية.' },
  { code: 'Q-R4', indicator: 'I-3.3.1', point: 'end', text: 'لدي الرغبة في الاستمرار والتسجيل في برنامج قادم.' },
  // فاعلية الأنشطة والتطبيقات — 3 أسئلة (BR-09)
  { code: 'Q-A1', indicator: 'I-2.3.2', point: 'activity', text: 'كان النشاط مفيدًا وأضاف لي معرفة أو مهارة جديدة.' },
  { code: 'Q-A2', indicator: 'I-2.3.2', point: 'activity', text: 'كان تنظيم النشاط وإدارته جيدًا.' },
  { code: 'Q-A3', indicator: 'I-2.3.2', point: 'activity', text: 'أرغب في المشاركة في أنشطة مشابهة مستقبلًا.' },
];

export const LIKERT = [
  { value: 5, label: 'موافق بشدة' },
  { value: 4, label: 'موافق' },
  { value: 3, label: 'محايد' },
  { value: 2, label: 'غير موافق' },
  { value: 1, label: 'غير موافق بشدة' },
];

/** أدوات قياس الأثر — وحدة مستقلة خارج مقياس الـ300. */
export const IMPACT_KINDS = [
  { value: 'pre', label: 'اختبار قبلي' },
  { value: 'post', label: 'اختبار بعدي' },
  { value: 'practical', label: 'تقييم عملي / تطبيقي' },
];

export const impactKindLabel = (kind) =>
  IMPACT_KINDS.find((k) => k.value === kind)?.label || kind;

/** الحد الأدنى المقبول لنسبة الاستجابة في الاستبانات. */
export const DEFAULT_MIN_RESPONSE_RATE = 70;
